version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=medusa_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    # env_file:
    #   - ./.env
    ports:
      - 5432:5432
volumes:
  postgres-db:

